name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cpp: [11, 14, 17]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.cpp }} ..
        
    - name: Build
      run: |
        cd build
        make -j4
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Run Python tests
      run: |
        pip install pytest
        python -m pytest tests/