name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cpp: [11, 14, 17]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew update
          brew install cmake
        fi
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.cpp }} ..
        
    - name: Build
      run: |
        cd build
        make -j4
    - name: Run Python tests
      run: |
        pip install pytest
        python -m pytest tests/
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Cache brew (macOS)
      if: runner.os == 'macOS'
      uses: actions/cache@v3
      with:
        path: /usr/local/Homebrew
        key: ${{ runner.os }}-brew-${{ hashFiles('**/CMakeLists.txt') }}